/* Do not alter. Auto generated file */

module.exports = {
	"delicious": "<div class=\"socialfeed-item socialfeed-delicious\">\n  <i class=\"socialfeed-icon icon-link\"></i>\n  <header>\n    <h2><a href=\"{u}\">{d}</a></h2>\n    <time datetime=\"{dt}\">{time_since}</time>\n  </header>\n  <div class=\"socialfeed-body\">\n    {n}\n  </div>\n</div>",
	"disqus": "<div class=\"socialfeed-item socialfeed-disqus\">\n  <i class=\"socialfeed-icon icon-comment-alt\"></i>\n  <header>\n    <h2><a href=\"{profile_url}\">{author_name}</a></h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n  <div class=\"socialfeed-body\">\n    {message}\n  </div>\n</div>",
	"github_create": "<div class=\"socialfeed-item socialfeed-github socialfeed-github-create\">\n  <i class=\"socialfeed-icon icon-github\"></i>\n  <header>\n    <h2>\n      <a href=\"{profile_url}\">{username}</a> created repository <a href=\"{repo_url}\">{repo_name}</a>\n    </h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n</div>",
	"github_createbranch": "<div class=\"socialfeed-item socialfeed-github socialfeed-github-createbranch\">\n  <i class=\"socialfeed-icon icon-github\"></i>\n  <header>\n    <h2>\n      <a href=\"{profile_url}\">{username}</a>\n      created branch <a href=\"{branchurl}\">{branch_name}</a>\n      at <a href=\"{repo_url}\">{repo_name}</a></h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n</div>",
	"github_fork": "<div class=\"socialfeed-item socialfeed-github socialfeed-github-fork\">\n  <i class=\"socialfeed-icon icon-github\"></i>\n  <header>\n    <h2>\n      <a href=\"{profile_url}\">{username}</a>\n      forked repository <a href=\"{repo_url}\">{repo_name}</a>\n      to <a href=\"{forkee_url}\">{forkee_name}</a>\n    </h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n</div>",
	"github_issue": "<div class=\"socialfeed-item socialfeed-github socialfeed-github-issue\">\n  <i class=\"socialfeed-icon icon-github\"></i>\n  <header>\n    <h2>\n      <a href=\"{profile_url}\">{username}</a>\n      {action} issue <a href=\"{issue_url}\">{issue_name}</a>\n    </h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n  <div class=\"socialfeed-body\">\n    {title}\n  </div>\n</div>",
	"github_pullrequest": "<div class=\"socialfeed-item socialfeed-github socialfeed-github-pull-request\">\n  <i class=\"socialfeed-icon icon-github\"></i>\n  <header>\n    <h2>\n      <a href=\"{profile_url}\">{username}</a>\n      {action} pull request <a href=\"{pullrequest_url}\">{pullrequest_name}</a>\n    </h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n  <div class=\"socialfeed-body\">\n    {title}\n  </div>\n</div>",
	"github_push": "<div class=\"socialfeed-item socialfeed-github socialfeed-github-push\">\n  <i class=\"socialfeed-icon icon-github\"></i>\n  <header>\n    <h2>\n      <a href=\"{profile_url}\">{username}</a>\n      pushed to <a href=\"{repo_url}\">{repo_name}</a>\n    </h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n  <ul class=\"socialfeed-commit-list\">\n    <li>\n      <a href=\"{commit_url}\">{commit}</a>\n      <span>{commit_message}</span>\n    </li>\n  </ul>\n</div>",
	"github_watch": "<div class=\"socialfeed-item socialfeed-github socialfeed-github-watch\">\n  <i class=\"socialfeed-icon icon-github\"></i>\n  <header>\n    <h2><a href=\"{profile_url}\">{username}</a> starred <a href=\"{repo_url}\">{repo_name}</a></h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n</div>",
	"rss": "<div class=\"socialfeed-item socialfeed-rss\">\n  <i class=\"socialfeed-icon icon-rss\"></i>\n  <header>\n    <h2>\n      New blog post at\n      <a href=\"{blogurl}\">{blogname}</a>\n    </h2>\n    <time datetime=\"{date}\">{time_since}</time>\n  </header>\n  <div class=\"socialfeed-body\">\n    <a href=\"{url}\">{title}</a>\n  </div>\n</div>",
	"tumblr": "<div class=\"socialfeed-item socialfeed-tumblr\">\n  <i class=\"socialfeed-icon icon-tumblr\"></i>\n  <header>\n    <h2><a href=\"{post_url}\">{title}</a></h2>\n    <time datetime=\"{date}\">{time_since}</time>\n  </header>\n  <div class=\"socialfeed-body\">\n    {body}\n\n    <p>Notes: {note_count}</p>\n  </div>\n</div>",
	"vimeo_add_comment": "<div class=\"socialfeed-item socialfeed-vimeo socialfeed-vimeo-comment\">\n  <i class=\"socialfeed-icon icon-play-sign\"></i>\n  <header>\n    <h2><a href=\"{user_url}\">{user_name}</a> commented on <a href=\"{video_url}\">{video_title}</a> on Vimeo</h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n\n  <div class=\"socialfeed-body\">\n    {comment_text}\n  </div>\n</div>",
	"vimeo_like": "<div class=\"socialfeed-item socialfeed-vimeo socialfeed-vimeo-like\">\n  <i class=\"socialfeed-icon icon-play-sign\"></i>\n  <header>\n    <h2><a href=\"{user_url}\">{user_name}</a> liked a <a href=\"{video_url}\">video on Vimeo</a></h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n\n  <div class=\"socialfeed-body\">\n    <h3><a href=\"{video_url}\">{video_title}</a></h3>\n    <a href=\"{video_url}\">\n      <img src=\"{video_thumbnail_large}\" alt=\"{video_title}\">\n    </a>\n  </div>\n</div>",
	"vimeo_upload": "<div class=\"socialfeed-item socialfeed-vimeo socialfeed-vimeo-upload\">\n  <i class=\"socialfeed-icon icon-play-sign\"></i>\n  <header>\n    <h2><a href=\"{user_url}\">{user_name}</a> uploaded a <a href=\"{video_url}\">video on Vimeo</a></h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n\n  <div class=\"socialfeed-body\">\n    <h3><a href=\"{video_url}\">{video_title}</a></h3>\n    <a href=\"{video_url}\">\n      <img src=\"{video_thumbnail_large}\" alt=\"{video_title}\">\n    </a>\n  </div>\n</div>",
	"youtubeuploads": "<div class=\"socialfeed-item socialfeed-youtube socialfeed-youtube-upload\">\n  <i class=\"socialfeed-icon icon-play-circle\"></i>\n  <header>\n    <h2><a href=\"{profile_url}\">{username}</a> added a video: <a href=\"{video_url}\">{video_name}</a></h2>\n    <time datetime=\"{created_at}\">{time_since}</time>\n  </header>\n  <div class=\"socialfeed-body\">\n    <iframe class=\"youtube-preview\"\n      src=\"http://www.youtube.com/embed/{entry_id}?wmode=transparent&amp;HD=0&amp;rel=0&amp;showinfo=0&amp;controls=1&amp;autoplay=1\"\n      frameborder=\"0\"\n      allowfullscreen>\n    </iframe>\n    <p>{desc}</p>\n  </div>\n</div>",

};